const { v4: uuidv4 } = require('uuid');

exports.seed = function (knex) {
  return knex('usuarios')
    .del()
    .then(() => knex('usuarios').insert([
      {
        id_usuario: uuidv4(),
        email: "gnmf2000@gmail.com",
        senha: "senhateste",
        nome: "Gabriel",
        sobrenome: "Nunes Monteiro Ferreira",
        cpf: "49835719810",
        cep: "03535000",
        uf: "SP",
        city: "São Paulo",
        street: "Av Doutor Bernardino Brito Fonseca de Carvalho",
        number: "1647",
        complement: "gamelinha",
        foto: "Lorem Ipsum",
        descricao: "Sou o Gabriel Nunes",
        link_deezer: null,
        link_facebook: "Gabriel Nunes Monteiro Ferreira",
        link_instagram: null,
        link_spotify: null,
        link_youtube: null,
        link_twitch: null,
        is_professor: false,
        is_freelancer: true,
        titulo_profissional: null,
        descricao_freelancer: null,
        experiencia_profissional: null,
        principais_habilidades: null,
        is_professor_aprovado: false,
        is_freelancer_aprovado: false,
        pergunta_professor_1: null,
        pergunta_professor_2: null,
        pergunta_professor_3: null,
        freelancer_verificado: null
      },
      {
        id_usuario: uuidv4(),
        email: "thais_larissa12@gmail.com",
        senha: "senhateste",
        nome: "Thais",
        sobrenome: "Larissa Campos Neves",
        cpf: "49835719810",
        cep: "03535123",
        uf: "SP",
        city: "São Paulo",
        street: "Av Doutor Bernardino Brito Fonseca de Carvalho",
        number: "1647",
        complement: "gamelinha",
        foto: "Lorem Ipsum",
        descricao: "Sou o Gabriel Nunes",
        link_deezer: null,
        link_facebook: "Gabriel Nunes Monteiro Ferreira",
        link_instagram: null,
        link_spotify: null,
        link_youtube: null,
        link_twitch: null,
        is_professor: false,
        is_freelancer: true,
        titulo_profissional: null,
        descricao_freelancer: null,
        experiencia_profissional: null,
        principais_habilidades: null,
        is_professor_aprovado: false,
        is_freelancer_aprovado: false,
        pergunta_professor_1: null,
        pergunta_professor_2: null,
        pergunta_professor_3: null,
        freelancer_verificado: null
      },
      
    ]));
};
